version: "3.8"

services:
  nacos:
    image: nacos/nacos-server:v3.1.1
    container_name: nacos
    environment:
      MODE: standalone
      NACOS_AUTH_ENABLE: "false"
    ports:
      - "8848:8848"

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT_DOCKER}"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init:/docker-entrypoint-initdb.d
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

  redis:
    container_name: redis
    image: redis:7
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT_DOCKER}"

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: auth/Dockerfile
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NACOS_SERVER_ADDR=nacos:8848
      - CLIENT_REDIRECT_URI=http://localhost:${CLIENT_PORT}/login/oauth2/code/my-registration
    ports:
      - "${AUTH_PORT}:${AUTH_PORT_DOCKER}"
    depends_on:
      - nacos
      - postgres

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NACOS_SERVER_ADDR=nacos:8848
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT_DOCKER}"
    depends_on:
      - nacos
      - auth
      - redis

  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NACOS_SERVER_ADDR=nacos:8848
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT_DOCKER}"
    network_mode: "host"
    depends_on:
      - nacos
      - auth
