create schema if not exists my_schema;

create table if not exists "my_schema"."users" (
    "ID" bigint generated by default as identity primary key,
    "USERNAME" varchar(100) not null unique,
    "PASSWORD" varchar(200) not null,
    "EMAIL" varchar(200) not null unique,
    "CREATED_AT" timestamp with time zone default current_timestamp,
    "UPDATED_AT" timestamp with time zone default current_timestamp,
    "AUTHORITIES" varchar(500) not null
);
