create schema if not exists my_schema;

create table if not exists my_schema.users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    password varchar(200) not null,
    email varchar(200) not null unique,
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp,
    authorities varchar(500) not null
);
