package com.example.auth.config;

import javax.sql.DataSource;
import java.nio.file.Path;
import java.sql.Timestamp;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import static org.assertj.core.api.Assertions.assertThat;

@Testcontainers
class PostgresUsersSchemaCompatibilityTest {

    private static final String USER_LOOKUP_SQL = """
            SELECT "my_schema"."users"."id" AS "id",
                   "my_schema"."users"."email" AS "email",
                   "my_schema"."users"."username" AS "username",
                   "my_schema"."users"."password" AS "password",
                   "my_schema"."users"."updated_at" AS "updated_at",
                   "my_schema"."users"."created_at" AS "created_at"
            FROM "my_schema"."users"
            WHERE "my_schema"."users"."username" = ?
            """;

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16");

    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        this.jdbcTemplate = new JdbcTemplate(dataSource());
        this.jdbcTemplate.execute("drop schema if exists my_schema cascade");
    }

    @Test
    void usersSqlCreatesPostgresColumnsThatJdbcQueriesCanRead() {
        new ResourceDatabasePopulator(new ClassPathResource("sql/users.sql")).execute(dataSource());

        jdbcTemplate.update("""
                insert into "my_schema"."users" (
                    "username",
                    "password",
                    "email",
                    "created_at",
                    "updated_at"
                ) values (?, ?, ?, current_timestamp, current_timestamp)
                """,
                "user",
                "{noop}password",
                "user@example.com"
        );

        String username = jdbcTemplate.queryForObject(
                USER_LOOKUP_SQL,
                (rs, rowNum) -> rs.getString("username"),
                "user"
        );

        assertThat(username).isEqualTo("user");
    }

    @Test
    void usersSqlMigratesLegacyAuthoritiesColumnToNormalizedTable() {
        jdbcTemplate.execute("create schema if not exists my_schema");
        jdbcTemplate.execute("""
                create table my_schema.users (
                    id bigint generated by default as identity primary key,
                    username varchar(100) not null unique,
                    password varchar(200) not null,
                    email varchar(200) not null unique,
                    created_at timestamp default current_timestamp,
                    updated_at timestamp default current_timestamp,
                    authorities varchar(500) not null
                )
                """);

        jdbcTemplate.update("""
                insert into my_schema.users (
                    username,
                    password,
                    email,
                    created_at,
                    updated_at,
                    authorities
                ) values (?, ?, ?, current_timestamp, current_timestamp, ?)
                """,
                "legacy-user",
                "{noop}password",
                "legacy-user@example.com",
                "ROLE_USER ROLE_ADMIN"
        );

        new ResourceDatabasePopulator(new ClassPathResource("sql/users.sql")).execute(dataSource());

        assertThat(tableCount("user_authorities")).isEqualTo(1);
        assertThat(columnCount("users", "authorities")).isZero();
        assertThat(jdbcTemplate.queryForList("""
                select ua.authority
                from my_schema.user_authorities ua
                join my_schema.users u on u.id = ua.user_id
                where u.username = ?
                order by ua.authority
                """, String.class, "legacy-user"))
                .containsExactly("ROLE_ADMIN", "ROLE_USER");
    }

    @Test
    void dockerComposeInitScriptSeedsUserPasswordAs1234() {
        new ResourceDatabasePopulator(dockerComposeInitScript()).execute(dataSource());

        String encodedPassword = jdbcTemplate.queryForObject(
                "select password from my_schema.users where username = ?",
                String.class,
                "user"
        );

        assertThat(new BCryptPasswordEncoder().matches("1234", encodedPassword)).isTrue();
    }

    @Test
    void dockerComposeInitScriptCreatesNormalizedTablesWithoutLegacyClientTable() {
        new ResourceDatabasePopulator(dockerComposeInitScript()).execute(dataSource());

        assertThat(tableCount("client")).isZero();
        assertThat(tableCount("oauth2_registered_client")).isEqualTo(1);
        assertThat(tableCount("user_authorities")).isEqualTo(1);
    }

    @Test
    void dockerComposeInitScriptRefreshesUpdatedAtOnUpdate() throws Exception {
        new ResourceDatabasePopulator(dockerComposeInitScript()).execute(dataSource());

        Timestamp beforeUpdate = jdbcTemplate.queryForObject(
                "select updated_at from my_schema.users where username = ?",
                Timestamp.class,
                "user"
        );

        Thread.sleep(1000);

        jdbcTemplate.update(
                "update my_schema.users set email = ? where username = ?",
                "updated-user@example.com",
                "user"
        );

        Timestamp afterUpdate = jdbcTemplate.queryForObject(
                "select updated_at from my_schema.users where username = ?",
                Timestamp.class,
                "user"
        );

        assertThat(afterUpdate).isAfter(beforeUpdate);
    }

    private DataSource dataSource() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName(postgres.getDriverClassName());
        dataSource.setUrl(postgres.getJdbcUrl());
        dataSource.setUsername(postgres.getUsername());
        dataSource.setPassword(postgres.getPassword());
        return dataSource;
    }

    private Resource dockerComposeInitScript() {
        Path scriptPath = Path.of("").toAbsolutePath()
                .resolve("../postgres/init/init.sql")
                .normalize();
        return new FileSystemResource(scriptPath);
    }

    private int tableCount(String tableName) {
        return jdbcTemplate.queryForObject("""
                select count(*)
                from information_schema.tables
                where table_schema = 'my_schema'
                  and table_name = ?
                """, Integer.class, tableName);
    }

    private int columnCount(String tableName, String columnName) {
        return jdbcTemplate.queryForObject("""
                select count(*)
                from information_schema.columns
                where table_schema = 'my_schema'
                  and table_name = ?
                  and column_name = ?
                """, Integer.class, tableName, columnName);
    }
}
