# local
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth
          jws-algorithms: RS512
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

server:
  port: 8080

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI}
          jws-algorithms: RS512
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}

server:
  port: ${GATEWAY_PORT}

---
# common
spring:
  application:
    name: gateway
  messages:
    basename: messages
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    gateway:
      server:
        webflux:
          default-filters:
            - name: LogFilter
          routes:
            - id: route_auth
              uri: lb://auth
              predicates:
                - Path=/auth/**
              filters:
                - PreserveHostHeader
                - SetRequestHeader=X-Forwarded-Prefix, /auth
                - RewritePath=/auth/?(?<segment>.*), /$\{segment}
                - name: RequestSize
                  args:
                    maxSize: 5000000
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 100
                      burstCapacity: 100
                      requestedTokens: 1
                    key-resolver: "#{@myKeyResolver}"
          redis-rate-limiter:
            include-headers: false
          httpclient:
            connect-timeout: 10000
            response-timeout: 10s
  data:
    redis:
      time-to-live: 3600000

app:
  logging:
    path: ${LOG_PATH:./logs}
