# local
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.gateway.auth-server.issuer-uri}
          jws-algorithms: RS512
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

app:
  gateway:
    auth-server:
      issuer-uri: ${AUTH_ISSUER_URI:http://localhost:8080/auth}
    rate-limit:
      replenish-rate: ${GATEWAY_RATE_LIMIT_REPLENISH_RATE:100}
      burst-capacity: ${GATEWAY_RATE_LIMIT_BURST_CAPACITY:100}
      requested-tokens: ${GATEWAY_RATE_LIMIT_REQUESTED_TOKENS:1}

server:
  port: 8080

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.gateway.auth-server.issuer-uri}
          jws-algorithms: RS512
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}

app:
  gateway:
    auth-server:
      issuer-uri: ${AUTH_ISSUER_URI}
    rate-limit:
      replenish-rate: ${GATEWAY_RATE_LIMIT_REPLENISH_RATE:100}
      burst-capacity: ${GATEWAY_RATE_LIMIT_BURST_CAPACITY:100}
      requested-tokens: ${GATEWAY_RATE_LIMIT_REQUESTED_TOKENS:1}

server:
  port: ${GATEWAY_PORT}

---
# common
spring:
  application:
    name: gateway
  messages:
    basename: messages
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    gateway:
      server:
        webflux:
          default-filters:
            - name: LogFilter
          routes:
            - id: route_auth
              uri: lb://auth
              predicates:
                - Path=/auth/**
              filters:
                - PreserveHostHeader
                - SetRequestHeader=X-Forwarded-Prefix, /auth
                - RewritePath=/auth/?(?<segment>.*), /$\{segment}
                - name: RequestSize
                  args:
                    maxSize: 5000000
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: ${app.gateway.rate-limit.replenish-rate}
                      burstCapacity: ${app.gateway.rate-limit.burst-capacity}
                      requestedTokens: ${app.gateway.rate-limit.requested-tokens}
                    key-resolver: "#{@myKeyResolver}"
          redis-rate-limiter:
            include-headers: false
          httpclient:
            connect-timeout: 10000
            response-timeout: 10s
  data:
    redis:
      time-to-live: 3600000

app:
  logging:
    path: ${LOG_PATH:./logs}
