# local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/my_db?currentSchema=my_schema
    username: postgres
    password: 1234
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/oauth2-registered-client.sql
        - classpath:sql/oauth2-authorization.sql
        - classpath:sql/oauth2-authorization-consent.sql
        - classpath:sql/users.sql
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

server:
  port: 9000

app:
  auth:
    issuer: http://localhost:8080/auth
  client:
    redirect-uri: http://127.0.0.1:8011/login/oauth2/code/my-registration

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/oauth2-registered-client.sql
        - classpath:sql/oauth2-authorization.sql
        - classpath:sql/oauth2-authorization-consent.sql
        - classpath:sql/users.sql
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}

server:
  port: ${AUTH_PORT}

app:
  auth:
    issuer: ${AUTH_ISSUER_URI}
  client:
    redirect-uri: ${CLIENT_REDIRECT_URI}

---
# common
spring:
  application:
    name: auth
  messages:
    basename: messages

server:
  shutdown: graceful
