# local
spring:
  config:
    activate:
      on-profile: local
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

server:
  port: 9000

app:
  auth:
    issuer: http://127.0.0.1:9000
  client:
    redirect-uri: http://127.0.0.1:8011/login/oauth2/code/my-registration

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}

server:
  port: ${AUTH_PORT}

app:
  auth:
    issuer: ${AUTH_ISSUER_URI}
  client:
    redirect-uri: ${CLIENT_REDIRECT_URI}

---
# common
spring:
  application:
    name: auth
  messages:
    basename: messages

server:
  shutdown: graceful
