# local
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          my-registration:
            provider: my-provider
            client-id: client_id_1
            client-secret: client_secret_1
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          my-provider:
            issuer-uri: http://localhost:8080/auth
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

server:
  port: 8011
  servlet:
    session:
      cookie:
        name: CLIENTSESSION

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        registration:
          my-registration:
            provider: my-provider
            client-id: client_id_1
            client-secret: client_secret_1
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          my-provider:
            issuer-uri: ${AUTH_ISSUER_URI}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}

server:
  port: ${CLIENT_PORT}
  servlet:
    session:
      cookie:
        name: CLIENTSESSION

---
# common
spring:
  application:
    name: client
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    nacos:
      discovery:
        register-enabled: false
