CREATE SCHEMA IF NOT EXISTS my_schema;

-- ------------------------------------------------------------

DROP TABLE IF EXISTS my_schema.client;

CREATE TABLE IF NOT EXISTS my_schema.oauth2_registered_client (
    id varchar(100) PRIMARY KEY,
    client_id varchar(100) NOT NULL UNIQUE,
    client_id_issued_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    client_secret varchar(200) DEFAULT NULL,
    client_secret_expires_at timestamp with time zone DEFAULT NULL,
    client_name varchar(200) NOT NULL,
    client_authentication_methods varchar(1000) NOT NULL,
    authorization_grant_types varchar(1000) NOT NULL,
    redirect_uris varchar(1000) DEFAULT NULL,
    post_logout_redirect_uris varchar(1000) DEFAULT NULL,
    scopes varchar(1000) NOT NULL,
    client_settings varchar(2000) NOT NULL,
    token_settings varchar(2000) NOT NULL
);

CREATE TABLE IF NOT EXISTS my_schema.oauth2_authorization (
    id varchar(100) PRIMARY KEY,
    registered_client_id varchar(100) NOT NULL,
    principal_name varchar(200) NOT NULL,
    authorization_grant_type varchar(100) NOT NULL,
    authorized_scopes varchar(1000) DEFAULT NULL,
    attributes text DEFAULT NULL,
    state varchar(500) DEFAULT NULL,
    authorization_code_value text DEFAULT NULL,
    authorization_code_issued_at timestamp with time zone DEFAULT NULL,
    authorization_code_expires_at timestamp with time zone DEFAULT NULL,
    authorization_code_metadata text DEFAULT NULL,
    access_token_value text DEFAULT NULL,
    access_token_issued_at timestamp with time zone DEFAULT NULL,
    access_token_expires_at timestamp with time zone DEFAULT NULL,
    access_token_metadata text DEFAULT NULL,
    access_token_type varchar(100) DEFAULT NULL,
    access_token_scopes varchar(1000) DEFAULT NULL,
    oidc_id_token_value text DEFAULT NULL,
    oidc_id_token_issued_at timestamp with time zone DEFAULT NULL,
    oidc_id_token_expires_at timestamp with time zone DEFAULT NULL,
    oidc_id_token_metadata text DEFAULT NULL,
    refresh_token_value text DEFAULT NULL,
    refresh_token_issued_at timestamp with time zone DEFAULT NULL,
    refresh_token_expires_at timestamp with time zone DEFAULT NULL,
    refresh_token_metadata text DEFAULT NULL,
    user_code_value text DEFAULT NULL,
    user_code_issued_at timestamp with time zone DEFAULT NULL,
    user_code_expires_at timestamp with time zone DEFAULT NULL,
    user_code_metadata text DEFAULT NULL,
    device_code_value text DEFAULT NULL,
    device_code_issued_at timestamp with time zone DEFAULT NULL,
    device_code_expires_at timestamp with time zone DEFAULT NULL,
    device_code_metadata text DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS my_schema.oauth2_authorization_consent (
    registered_client_id varchar(100) NOT NULL,
    principal_name varchar(200) NOT NULL,
    authorities varchar(1000) NOT NULL,
    PRIMARY KEY (registered_client_id, principal_name)
);

-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS my_schema.users (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   username varchar(100) NOT NULL UNIQUE,
   password varchar(200) NOT NULL,
   email varchar(200) NOT NULL UNIQUE,
   tenant_id varchar(100) NOT NULL DEFAULT 'tenant-default',
   created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS my_schema.user_authorities (
   user_id bigint NOT NULL REFERENCES my_schema.users (id) ON DELETE CASCADE,
   authority varchar(100) NOT NULL,
   PRIMARY KEY (user_id, authority)
);

CREATE OR REPLACE FUNCTION my_schema.set_users_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS '
BEGIN
   NEW.updated_at = CURRENT_TIMESTAMP;
   RETURN NEW;
END;
';

DROP TRIGGER IF EXISTS users_set_updated_at ON my_schema.users;

CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON my_schema.users
FOR EACH ROW
EXECUTE FUNCTION my_schema.set_users_updated_at();

INSERT INTO my_schema.users (username, password, email, tenant_id, created_at, updated_at)
VALUES ('user', '$2y$10$L4i8HB/QEWjrv.n4pyrYx.pPkbzUu7/QQMTHpm/uuq3MERPcua4p6', 'user@example.com', 'tenant-alpha', current_timestamp, current_timestamp)
ON CONFLICT (username) DO NOTHING;

INSERT INTO my_schema.user_authorities (user_id, authority)
SELECT u.id, 'ROLE_USER'
FROM my_schema.users u
WHERE u.username = 'user'
ON CONFLICT (user_id, authority) DO NOTHING;

-- ------------------------------------------------------------
